groups:
- name: auth-service-alerts
  rules:

  - alert: AuthServiceDown
    expr: up{job="auth-service"} == 0
    for: 30s
    labels:
      severity: critical
    annotations:
      summary: "Auth Service DOWN"
      description: "auth-service ne répond plus"

  - alert: HighJVMMemoryUsage
    expr: sum(jvm_memory_used_bytes{area="heap"})
          / sum(jvm_memory_max_bytes{area="heap"}) > 0.8
    for: 1m
    labels:
      severity: warning
    annotations:
      summary: "High JVM Memory Usage"
      description: "Heap JVM > 80%"

  - alert: HighCPUUsage
    expr: process_cpu_usage > 0.8
    for: 1m
    labels:
      severity: warning
    annotations:
      summary: "High CPU Usage"
      description: "CPU > 80%"

  - alert: HighDBConnections
    expr: hikaricp_connections_active
          / hikaricp_connections_max > 0.8
    for: 1m
    labels:
      severity: warning
    annotations:
      summary: "High DB connections usage"
      description: "DB connections > 80%"
