apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-alerts
  namespace: monitoring
data:
  alert-rules.yml: |
    groups:
    - name: auth-service-alerts
      rules:

      - alert: AuthServiceDown
        expr: up{job="auth-service"} == 0
        labels:
          severity: critical
          service: auth-service
        annotations:
          summary: "Auth Service DOWN"
          description: "auth-service ne répond plus"

      - alert: HighJVMMemoryUsage
        expr: |
          sum by (job) (
            jvm_memory_used_bytes{job="auth-service", area="heap"}
          )
          /
          sum by (job) (
            jvm_memory_max_bytes{job="auth-service", area="heap"}
          ) > 0.8
        labels:
          severity: warning
          service: auth-service
        annotations:
          summary: "High JVM Memory Usage"
          description: "Heap JVM > 80%"

      - alert: HighCPUUsage
        expr: process_cpu_usage{job="auth-service"} > 0.8
        labels:
          severity: warning
          service: auth-service
        annotations:
          summary: "High CPU Usage"
          description: "CPU > 80%"

      - alert: HighDBConnections
        expr: |
          hikaricp_connections_active{job="auth-service"}
          /
          hikaricp_connections_max{job="auth-service"} > 0.8
        labels:
          severity: warning
          service: auth-service
        annotations:
          summary: "High DB connections usage"
          description: "DB connections > 80%"
