server:
  port: 8081

spring:
  application:
    name: auth-service

jwt:
  secret: MaCleUltraSecretePourJWT256BitsSuperLongue1234567890
  expiration: 86400000
  refresh-expiration: 604800000

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  endpoint:
    prometheus:
      enabled: true
