apiVersion: v1
kind: ConfigMap
metadata:
  name: auth-config
  namespace: gestion-projet
data:
  SERVER_PORT: "8081"

  # ✅ ACTUATOR SUR PORT DÉDIÉ
  MANAGEMENT_SERVER_PORT: "8082"
  MANAGEMENT_ENDPOINTS_WEB_BASE_PATH: "/actuator"

  SPRING_APPLICATION_NAME: "auth-service"

  # ✅ JDBC CORRIGÉ (PAS DE &amp;)
  SPRING_DATASOURCE_URL: "jdbc:postgresql://ep-wandering-rice-a4uh9a3k.us-east-1.aws.neon.tech/neondb?sslmode=require&channel_binding=require"

  SPRING_JPA_HIBERNATE_DDL_AUTO: "update"
  SPRING_JPA_SHOW_SQL: "true"

  HIBERNATE_DIALECT: "org.hibernate.dialect.PostgreSQLDialect"
  HIBERNATE_FORMAT_SQL: "true"

  LOGGING_LEVEL_ROOT: "INFO"
  LOGGING_LEVEL_ORG_SPRINGFRAMEWORK_WEB: "DEBUG"
  LOGGING_LEVEL_ORG_SPRINGFRAMEWORK_SECURITY: "DEBUG"
  LOGGING_LEVEL_ORG_HIBERNATE_SQL: "DEBUG"
