apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-deployment
  namespace: gestion-projet
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-service
  template:
    metadata:
      labels:
        app: user-service
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8081"
        prometheus.io/path: "/actuator/prometheus"
    spec:
      containers:
        - name: user-service
          image: nour292/user-service:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8081

          envFrom:
            - configMapRef:
                name: user-config
            - secretRef:
                name: user-secret

          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8081
            initialDelaySeconds: 20
            periodSeconds: 10

          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8081
            initialDelaySeconds: 40
            periodSeconds: 20
