apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-deployment
  namespace: gestion-projet
spec:
  replicas: 2
  selector:
    matchLabels:
      app: auth-service
  template:
    metadata:
      labels:
        app: auth-service
    spec:
      containers:
        - name: auth-service
          image: nour292/auth-service:build-103
          imagePullPolicy: Always
          ports:
            - containerPort: 8081

          # ✅ CHARGER TOUTE LA CONFIG D’UN COUP
          envFrom:
            - configMapRef:
                name: auth-config
            - secretRef:
                name: auth-secret

          # ✅ PROBES (IMPORTANT POUR JENKINS)
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8081
            initialDelaySeconds: 20
            periodSeconds: 10

          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8081
            initialDelaySeconds: 40
            periodSeconds: 20
